before:
  hooks:
    - go mod download

builds:
-
  id: "goqtt"
  skip: true

- 
  id: "connect"
  dir: examples
  main: ./connect/main.go
  binary: examples/connect
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - arm64
    - arm
  goarm:
    - 7

-
  id: "publish"
  dir: examples
  main: ./publish/main.go
  binary: examples/publish
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - arm64
    - arm
  goarm:
    - 7

- 
  id: "subscribe"
  dir: examples
  main: ./subscribe/main.go
  binary: examples/subscribe
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - arm64
    - arm
  goarm:
    - 7

archives:
- replacements:
    linux: Linux
    darwin: macOS

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - 'README'
      - '^docs:'
      - '^test:'
