version: "3.8"
services:
  broker:
    build: ./broker
    command: -port 1885
    networks:
      - goqtt
  subscribe:
    build: ./subscribe
    command: -server broker -port 1885
    depends_on:
      - broker
    networks:
      - goqtt
  publish:
    build: ./publish
    command: -server broker -port 1885 -message "hi from compose"
    depends_on:
      - broker
      - subscribe
    networks:
      - goqtt

networks:
  goqtt: